import React, { useState } from "react";
import "./App.css";
import "bootstrap/dist/css/bootstrap.css";
import { Row, Col, Card, Container } from "react-bootstrap";
import SearchBar from "./Components/SearchBar";
import SearchResults from "./Components/SearchResults";
import NominationsList from "./Components/NominationsList";
import key from "./apikey.json"; //needs to be generated by distributor at omdbapi.com
import OMDB from "./Func/OMDB";
// state should be saved here
function App() {
  const database = new OMDB(key.key);
  const [state, setState] = useState({
    movieSearch: "Movie Title",
    movieSearchResults: [],
    movieNominees: [],
  });
  //receives search results as list of movie objects
  function onSearchSubmitted(movieSearch) {
    const searchPromise = database.search(movieSearch);
    searchPromise.then((searchObject) => {
      let newState = { ...state };
      state.movieSearchResults = searchObject.Search;
      setState(newState);
    });
    return searchPromise;
  }
  // Movie Search is what's in the textbox, MovieSearchResults is a list of movie objects that are the results,
  //Movie nominees are the nominees
  return (
    <div className="App">
      <Container>
        <Row>
          <h2 className="title"> The Shopify Movers App</h2>
        </Row>
        <div className="Content">
          <Row className="pageRow">
            <Col align={"center"}>
              <Card className="searchCard">
                <Card.Body>
                  <Card.Title>Movie Title</Card.Title>
                  <SearchBar onSearchSubmitted={onSearchSubmitted} />
                </Card.Body>
              </Card>
            </Col>
          </Row>
          <Row className="pageRow">
            <Col>
              <Card className="infoCard">
                <Card.Body>
                  <Card.Title>Results</Card.Title>
                  <SearchResults results={state.movieSearchResults} />
                </Card.Body>
              </Card>
            </Col>
            <Col>
              <Card className="infoCard">
                <Card.Body>
                  <Card.Title>Nominations</Card.Title>
                  <NominationsList />
                </Card.Body>
              </Card>
            </Col>
          </Row>
        </div>
      </Container>
    </div>
  );
} //onSearchReceived might be anti-pattern for react

export default App;
