import React, { useState } from "react";
import "./App.css";
import "bootstrap/dist/css/bootstrap.css";
import { Row, Col, Card, Container, Alert } from "react-bootstrap";
import SearchBar from "./Components/SearchBar";
import SearchResults from "./Components/SearchResults";
import NominationsList from "./Components/NominationsList";
import key from "./apikey.json"; //needs to be generated by distributor at omdbapi.com
import OMDB from "./Func/OMDB";

// state should be saved here

function App() {
  const database = new OMDB(key.key);
  const [state, setState] = useState({
    movieSearch: "Movie Title",
    movieSearchResults: [
      {
        Title: "Shrek",
        Year: "2001",
        imdbID: "tt0126029",
        Type: "movie",
        Poster:
          "https://m.media-amazon.com/images/M/MV5BOGZhM2FhNTItODAzNi00YjA0LWEyN2UtNjJlYWQzYzU1MDg5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
      },
    ],
    movieNominees: [],
    movieNotFoundError: false,
  });
  //receives search results as list of movie objects
  function onSearchSubmitted(movieSearch) {
    const searchPromise = database.search(movieSearch);

    searchPromise.then((searchObject) => {
      let errorResult = {
        Search: [
          {
            Title: "Movie Not Found",
            Year: "0",
            imdbID: "tt0126029",
            Type: "movie",
          },
        ],
      };

      let data = new Promise((resolve, reject) => {
        setTimeout(() => {
          let didSucceed = true; // adjust for testing
          didSucceed ? resolve(errorResult) : reject("Error");
        }, 1);
      });

      if (searchObject.status === 200) {
        data = searchObject.json();
      }

      data.then((actualStuff) => {
        let newState = { ...state };

        if (actualStuff.Response === "True") {
          newState.movieSearchResults = actualStuff.Search;
          newState.movieNotFoundError = false;
          setState(newState);
        } else {
          //console.log(actualStuff.Response);
          newState.movieNotFound = true;
          setState(newState);
        }
      });
    });

    return searchPromise;
  }
  // Add and remove from nominationslist
  function addToNominationsList(movieObject) {
    let nState = { ...state };
    nState.movieNominees.push(movieObject);
    setState(nState);
  }

  function removeFromNominationsList(index) {
    let nState = { ...state };

    if (index > -1) {
      nState.movieNominees.splice(index, 1);
    }

    setState(nState);
  }

  // Movie Search is what's in the textbox, MovieSearchResults is a list of movie objects that are the results,
  //Movie nominees are the nominees
  return (
    <div className="App">
      <Container>
        <Row>
          <h2 className="title"> The Shopify Movers App</h2>
        </Row>
        <div className="Content">
          <Alert variant={"success"} show={state.movieNominees.length >= 5}>
            {" "}
            You've reached 5 nominations! Good Job!
          </Alert>
          <Row className="pageRow">
            <Col align={"center"}>
              <Card className="searchCard">
                <Card.Body>
                  <Card.Title>Movie Title</Card.Title>
                  <SearchBar onSearchSubmitted={onSearchSubmitted} />
                </Card.Body>
              </Card>
            </Col>
          </Row>
          <Row className="pageRow">
            <Col>
              <Card className="infoCard">
                <Card.Body>
                  <Card.Title>Results</Card.Title>
                  <SearchResults
                    results={state.movieSearchResults}
                    movieError={state.movieNotFoundError}
                    addToNominationsList={addToNominationsList}
                    movieNominees={state.movieNominees}
                  />
                </Card.Body>
              </Card>
            </Col>
            <Col>
              <Card className="infoCard">
                <Card.Body>
                  <Card.Title>Nominations</Card.Title>
                  <NominationsList
                    nominations={state.movieNominees}
                    addToNominationsList={addToNominationsList}
                    removeFromNominationsList={removeFromNominationsList}
                  />
                </Card.Body>
              </Card>
            </Col>
          </Row>
        </div>
      </Container>
    </div>
  );
} //onSearchReceived might be anti-pattern for react

export default App;
